replicaCount: 4

image:
  repository: mlog/example-api
  pullPolicy: IfNotPresent
  tag: "latest"

# FastAPI application configuration
app:
  command: ["/app/venv/bin/uvicorn"]
  args: ["main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  port: 8000

serviceAccount:
  create: true

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
