{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "example-api.serviceAccountName" . }}
  labels:
    {{- include "example-api.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
